### ISSUE TITLE
Limpar "Consumo de Energia por Setor.xlsx"

### ISSUE THREAD

**Issue by tclcin** [scrrpfv/projeto-ip#4]
databases/Dados EPE/Consumo de Energia por Setor.xlsx

**Comment by scrrpfv** [comment]
Eu falei que tinha feito mas menti desculpa ToT

**Comment by scrrpfv** [comment]
KKKKKKKKKKK

**Comment by tclcin** [comment]
enlouqueci desculpe

**Comment by tclcin** [comment]
não será feito
